# Generated by Django 4.2.5 on 2025-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('food', models.IntegerField()),
                ('cafe', models.IntegerField()),
                ('other', models.IntegerField()),
                ('communal', models.IntegerField()),
                ('month_finish', models.BooleanField(default=False)),
            ],
        ),
    ]
